<template>
    <div id="create" class="create content">
        <h2 class="title">Create Your Guestimate</h2>
        <p class="subtitle">Begin with your target savings amount and timeframe</p>
        <Input
            name="target"
            :val="store.target.amount"
            :handleInput="updateStore('target', 'amount')"
            :formatter="currencyFormatter"
            noBorder
            class="target-input"
            label="Target Amount"
            tooltip="Your target savings goal. This number should not be adjusted for inflation."
        />
        <div class="slider-container">
            <Slider
                :val="store.target.years"
                :handleInput="updateStore('target', 'years')"
                min="1"
                max="80"
                tooltip
            />
        </div>
        <div class="panel-container">
            <div class="panel">
                <WalletIcon class="icon secondary" />
                <h4 class="panel__title">Annual</h4>
                <Input
                    name="income"
                    :val="store.inputs.income"
                    :handleInput="updateStore('inputs', 'income')"
                    :formatter="currencyFormatter"
                    class="panel__input"
                    color="secondary"
                    label="Net Income"
                    tooltip="Your annual income. Do not include income generated by assets."
                />
                <div class="panel__input panel__input--blank" />

                <h4 class="panel__title">Current</h4>
                <Input
                    name="assets"
                    :val="store.inputs.assets"
                    :handleInput="updateStore('inputs', 'assets')"
                    :formatter="currencyFormatter"
                    class="panel__input"
                    color="secondary"
                    label="Assets"
                    errorMessage="Oh no! Something isn't right"
                    tooltip="Your current assets. Stocks, bonds, cash, real estate and any other assets that generate income."
                />
                <h4 class="panel__title">Annual Growth Rate</h4>
                <div class="panel__flex">
                    <Input
                        name="growthStocks"
                        :val="store.inputs.growthRateStocks"
                        :handleInput="updateStore('inputs', 'growthRateStocks')"
                        :formatter="(val) => percentFormatter(val, 1)"
                        class="panel__input"
                        color="secondary"
                        label="Stocks %"
                        small
                        tooltip="Your expected average real return on stocks in your portfolio. This number should be inflation adjusted."
                        tooltipPlacement="right"
                    />
                    <Input
                        name="growthBonds"
                        :val="store.inputs.growthRateBonds"
                        :handleInput="updateStore('inputs', 'growthRateBonds')"
                        :formatter="(val) => percentFormatter(val, 1)"
                        class="panel__input"
                        color="secondary"
                        label="Bonds %"
                        small
                        tooltip="Your expected average real return on bonds in your portfolio. This number should be inflation adjusted."
                    />
                    <Input
                        name="growthCash"
                        :val="store.inputs.growthRateCash"
                        :handleInput="updateStore('inputs', 'growthRateCash')"
                        :formatter="(val) => percentFormatter(val, 1)"
                        class="panel__input"
                        color="secondary"
                        label="Cash %"
                        small
                        tooltip="Your expected  average real return on all other assets in your portfolio. This number should be inflation adjusted."
                        tooltipPlacement="left"
                    />
                </div>
            </div>

            <h1 class="seperator">-</h1>

            <div class="panel">
                <CreditCardIcon class="icon tertiary" />
                <h4 class="panel__title">Annual</h4>
                <Input
                    name="expenses"
                    :val="store.inputs.expenses"
                    :handleInput="updateStore('inputs', 'expenses')"
                    :formatter="currencyFormatter"
                    class="panel__input"
                    color="tertiary"
                    label="Expenses excl. Repayments"
                    tooltip="Your annual expenses. Do not include expenditures on repayment of debt (e.g. mortgage payments), enter these below."
                />
                <Input
                    name="repayments"
                    :val="store.inputs.repayments_base"
                    :handleInput="updateStore('inputs', 'repayments_base')"
                    :formatter="currencyFormatter"
                    class="panel__input"
                    color="tertiary"
                    label="Debt Repayments"
                    tooltip="Your annual expenditure on debt repayments, e.g. mortgage payments"
                />
                <h4 class="panel__title">Current</h4>
                <Input
                    name="liabilities"
                    :val="store.inputs.liabilities"
                    :handleInput="updateStore('inputs', 'liabilities')"
                    :formatter="currencyFormatter"
                    class="panel__input"
                    color="tertiary"
                    label="Debt"
                    tooltip="Your current outstanding balance on debt, e.g. mortgage"
                />
                <h4 class="panel__title">Annual Interest Rate</h4>
                <Input
                    name="interestRate"
                    :val="store.inputs.interestRateLiabilities"
                    :handleInput="updateStore('inputs', 'interestOnLiabilities')"
                    :formatter="(val) => percentFormatter(val, 1)"
                    class="panel__input"
                    color="tertiary"
                    label="Interest on Debt %"
                    tooltip="The average real rate of interest on your debt. This number should be inflation adjusted."
                />
            </div>
            <h1 class="seperator">=</h1>
            <div class="panel">
                <SaveIcon class="icon" />
                <h4 class="panel__title">Annual</h4>
                <Input
                    name="savings"
                    :val="store.inputs.income - store.inputs.expenses"
                    :formatter="currencyFormatter"
                    class="panel__input"
                    label="Savings"
                    disabled
                    tooltip="Your annual savings. The difference between your income and expenses."
                />
                <Input
                    name="savingsRepayments"
                    :val="
                        store.inputs.income +
                        store.inputs.repayments_base -
                        store.inputs.expenses
                    "
                    :formatter="currencyFormatter"
                    class="panel__input"
                    label="Savings & Repayments"
                    disabled
                    tooltip="Your annual savings plus repayments of debt. Repayments reduce debt which increases your net worth, similar to saving."
                />
                <h4 class="panel__title">Current</h4>
                <Input
                    name="newWorth"
                    :val="store.inputs.assets - store.inputs.liabilities"
                    :formatter="currencyFormatter"
                    class="panel__input"
                    label="Net Worth"
                    disabled
                    tooltip="Your current net worth. The difference between your assets and your liabilities (debt)"
                />
                <h4 class="panel__title">Portfolio Allocation</h4>
                <div class="panel__flex">
                    <Input
                        name="allocationStocks"
                        :val="store.inputs.allocationStocks"
                        :handleInput="updateStore('inputs', 'allocationStocks')"
                        :formatter="percentFormatter"
                        class="panel__input"
                        label="% Stocks"
                        small
                        tooltip="The proportion of your assets that will be held in stocks."
                        tooltipPlacement="right"
                    />
                    <Input
                        name="allocationBonds"
                        :val="store.inputs.allocationBonds"
                        :handleInput="updateStore('inputs', 'allocationBonds')"
                        :formatter="percentFormatter"
                        class="panel__input"
                        label="% Bonds"
                        small
                        tooltip="The proportion of your assets that will be held in bonds."
                    />
                    <Input
                        name="allocationCash"
                        :val="store.inputs.allocationCash"
                        :handleInput="updateStore('inputs', 'allocationCash')"
                        :formatter="percentFormatter"
                        class="panel__input"
                        label="% Cash"
                        small
                        tooltip="The proportion of your assets that will be held in cash."
                        tooltipPlacement="left"
                    />
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
//IMPORT
import { inject, watch, provide } from "vue";
import { useCalculatorStore } from "../../stores/calculator";
import { useFormatter } from "../../use/useFormatter";
import { Form, configure, useFormErrors, useForm } from "vee-validate";

import Input from "../Input.vue";
import Slider from "../Slider/Slider.vue";

import WalletIcon from "../../assets/icons/wallet.svg";
import CreditCardIcon from "../../assets/icons/credit-card.svg";
import SaveIcon from "../../assets/icons/save-money.svg";

// BREAKPOINTS
const breakpoints = inject("breakpoints");

// CALCUALTOR
const store = useCalculatorStore();
const { update, setHasErrors } = store;

const updateStore = (domain, name) => {
    return (val) => {
        update(domain, name, val);
    };
};

// FORMATTER
const { currencyFormatter, percentFormatter } = useFormatter();

// VALIDATION

configure({
    validateOnInput: true, // controls if `input` events should trigger validation with `handleChange` handler
});

const currencyRegex = "^\\-?\\$?[0-9][0-9,]*$";
const growthRateRegex = "^\\-?[0-9]+\\.?[0-9]?$";
const allocationRegex = "^[0-9]+\\.?[0-9]?$";

const schema = {
    target: (value) => {
        return validate(value, "Target", currencyRegex, 0, 10000000000, currencyFormatter);
    },
    income: (value) => {
        const isValid = validate(
            value,
            "Income",
            currencyRegex,
            0,
            100000000,
            currencyFormatter
        );
        if (isValid !== true) return isValid;
        if (exceeds(store.inputs.expenses + store.inputs.repayments_base, value))
            return "Must exceed expenses & repayments";
        return true;
    },
    assets: (value) => {
        return validate(value, "Assets", currencyRegex, 0, 100000000, currencyFormatter);
    },
    growthStocks: (value) => {
        return validate(value, "Rate", growthRateRegex, -50, 50, percentFormatter);
    },
    growthBonds: (value) => {
        return validate(value, "Rate", growthRateRegex, -50, 50, percentFormatter);
    },
    growthCash: (value) => {
        return validate(value, "Rate", growthRateRegex, -50, 50, percentFormatter);
    },
    expenses: (value) => {
        const isValid = validate(
            value,
            "Expenses",
            currencyRegex,
            0,
            100000000,
            currencyFormatter
        );
        if (isValid !== true) return isValid;
        if (exceeds(value, store.inputs.income)) return "Must be lower than income";
        return true;
    },
    repayments: (value) => {
        const isValid = validate(
            value,
            "Repayments",
            currencyRegex,
            0,
            100000000,
            currencyFormatter
        );
        if (isValid !== true) return isValid;
        if (exceeds(value, store.inputs.income)) return "Must be lower than income";
        return true;
    },
    liabilities: (value) => {
        return validate(value, "Debt", currencyRegex, 0, 100000000, currencyFormatter);
    },
    interestRate: (value) => {
        return validate(value, "Rate", growthRateRegex, -50, 50, percentFormatter);
    },
    allocationStocks: (value) => {
        return validate(value, "Rate", allocationRegex, 0, 100, percentFormatter);
    },
    allocationBonds: (value) => {
        return validate(value, "Rate", allocationRegex, 0, 100, percentFormatter);
    },
    allocationCash: (value) => {
        return validate(value, "Rate", allocationRegex, 0, 100, percentFormatter);
    },
};

const form = useForm({
    validationSchema: schema,
});

provide("form", form);
watch(form.errors, () => {
    setHasErrors(Object.keys(form.errors.value).length > 0);
});

function convertToNum(val) {
    if (!isNaN(val)) return val;
    return Number(val.replace(/[^0-9.-]+/g, ""));
}

function isNegative(num) {
    return Math.sign(num) === -1;
}
function isValidCurrency(value) {
    const pattern = "^\\-?\\$?[0-9][0-9,]*$";
    const re = new RegExp(pattern);
    return re.test(value);
}

function isEmpty(value) {
    return !(value && value.trim());
}

function exceeds(val1, val2) {
    return convertToNum(val1) > convertToNum(val2);
}

function isValidPattern(value, pattern) {
    const re = new RegExp(pattern);
    return re.test(value);
}

function validate(value, name, pattern, min, max, formatter) {
    if (isEmpty(value)) return "Required";
    if (!isValidPattern(value, pattern)) return "Invalid input";
    const numValue = convertToNum(value);
    if (isNegative(numValue) && min === 0) return `${name} must be positive`;
    if (numValue < min) return `${name} must be at least ${formatter(min)}`;
    if (numValue > max) return `${name} must not exceed ${formatter(max)}`;
    return true;
}
</script>

<style lang="scss" scoped>
.create {
    padding: 0 $mobileSidePadding;

    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    margin-bottom: $spacingL;

    .title {
        margin-bottom: $spacingXS;
    }

    .subtitle {
        max-width: 90%;
        margin-bottom: $spacingM;
    }

    .target-input {
        margin-bottom: $spacingL;
    }

    .slider-container {
        width: 100%;
        padding: 0 calc($mobileSidePadding + 2rem);
        margin-bottom: $spacingXL;
    }

    .panel-container {
        display: flex;
        flex-direction: column;
        gap: $spacingS;

        .seperator {
            display: block;
            margin-top: auto;
            margin-bottom: auto;
        }
        .panel {
            padding: $spacingL $spacingM $spacingXS $spacingM;
            border-radius: 0.5rem;
            background-color: rgba($colorPrimary, 5%);
            box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);

            .icon {
                height: 3.5rem;
                width: 3.5rem;
                margin-bottom: $spacingM;
                fill: $colorPrimary;

                &.secondary {
                    fill: $colorSecondary;
                }
                &.tertiary {
                    fill: $colorTertiary;
                }
            }

            &__title {
                font-weight: normal;
                color: $colorFontSubtle;
                text-align: left;
                margin-bottom: $spacingS;
            }

            &__input {
                margin-bottom: $spacingXS;
            }

            &__input--blank {
                height: 6.75rem;
                display: none;
            }

            &__flex {
                display: flex;
                justify-content: space-between;
            }
        }
    }
}

@media (min-width: $breakpointDesktop) {
    .create {
        .subtitle {
            height: $spacingXL;
        }

        .panel-container {
            width: 100%;
            display: flex;
            flex-direction: row;
            justify-content: space-around;
            margin-bottom: $spacingXL;
            gap: $spacingXS;

            .panel {
                &__input--blank {
                    display: block;
                }
            }
        }

        .seperator {
            font-size: 2rem;
        }
    }
}
</style>
